# -*- coding: utf-8 -*-
"""grid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjFDneEML1I6rBIAtnicWyR_f6qMNB1U
"""

def solve(N, A):
    if N == 0:
        return []

    lower = [0] * N
    upper = [0] * N
    lower[0] = upper[0] = A[0]

    for i in range(1, N):
        current = A[i]
        prev_lower = lower[i - 1]
        prev_upper = upper[i - 1]

        if current < prev_lower:
            lower[i] = current
            upper[i] = prev_lower
        elif current > prev_upper:
            lower[i] = prev_upper
            upper[i] = current
        else:
            lower[i] = current
            upper[i] = current

    bottom = [0] * N
    bottom[N - 1] = lower[N - 1]
    for i in range(N - 2, -1, -1):
        next_val = bottom[i + 1]
        if next_val < lower[i]:
            bottom[i] = lower[i]
        elif next_val > upper[i]:
            bottom[i] = upper[i]
        else:
            bottom[i] = next_val

    return bottom


def main():
    T = int(input())
    for _ in range(T):
        N = int(input())
        A = list(map(int, input().split()))
        result = solve(N, A)
        print(' '.join(str(x) for x in result))


if __name__ == '__main__':
    main()