# -*- coding: utf-8 -*-
"""Piezoelectric.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A3_B67pHffASyHThFpL2yiWl1L72O8z4

1
---
"""

def solve(L, W, E, R):
    """
    Return the number of laps needed to charge the car (rounded up)

    L: Length of car
    W: Width of car
    E: Amount of electricity to generate
    R: Electricity generated per unit distance
    """


    perimeter = 2 * (L + W)

    energy_per_lap = perimeter * R

    laps_needed = (E + energy_per_lap - 1) // energy_per_lap

    return laps_needed


def read_your_input():
    pass

def main():

    all_inputs = list(map(int, input().split()))

    T = all_inputs[0]

    current_index = 1
    for _ in range(T):
        L = all_inputs[current_index]
        W = all_inputs[current_index + 1]
        E = all_inputs[current_index + 2]
        R = all_inputs[current_index + 3]
        current_index += 4
        print(solve(L, W, E, R))

if __name__ == "__main__":
    main()

"""2"""

