# -*- coding: utf-8 -*-
"""TheBigBenFiles

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ncy1fTCOnu0kt3IXFYF7UqCxkKD0MkRk
"""

Test_cases = int(input())  # test cases

for _ in range(Test_cases):
    first = input()
    second = input()

    answer = list(first)  # string to list, because str can not modify directly

    p_b = 0  # B pointer

    for i in range(len(first)):  # range use, because we need index
        if p_b < len(second) and first[i] == second [p_b]:
            p_b += 1

        else:
            answer[i] = "#"
    print("".join(answer))