# -*- coding: utf-8 -*-
"""question 3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1le9QhVGnUlo0dDQNDQPmKh-_PYA1lhhe
"""

def solve(a, b):
    output =[]
    i = 0
    for char in a:
        if i < len(b) and char == b[i]:
            output.append(char)
            i = i+ 1
        else:
            output.append('#')
    return ''.join(output)

def main():
    t = int(input())
    for j in range(t):
        A = input().strip()
        B = input().strip()
        print(solve(A, B))
    pass

if __name__ == "__main__":
    main()

