# -*- coding: utf-8 -*-
"""4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjFDneEML1I6rBIAtnicWyR_f6qMNB1U
"""

def solve(K, N, M, P, Q, X, Y):
    def get_extended_gcd(a, b):
        if a == 0:
            return b, 0, 1
        gcd, x1, y1 = get_extended_gcd(b % a, a)
        return gcd, y1 - (b // a) * x1, x1

    earliest_hit_time = float('inf')
    best_asteroid_index = -1
    start_x, start_y = X[0], Y[0]

    for i in range(K):
        target_offset_x = (X[i] - start_x) % N
        target_offset_y = (Y[i] - start_y) % M

        gcd_x, inv_q, _ = get_extended_gcd(Q, N)
        if target_offset_x % gcd_x != 0:
            continue
        time_x, cycle_x = (inv_q * (target_offset_x // gcd_x)) % (N // gcd_x), N // gcd_x

        gcd_y, inv_p, _ = get_extended_gcd(P, M)
        if target_offset_y % gcd_y != 0:
            continue
        time_y, cycle_y = (inv_p * (target_offset_y // gcd_y)) % (M // gcd_y), M // gcd_y

        gcd_final, inv_cycle_x, _ = get_extended_gcd(cycle_x, cycle_y)
        if (time_y - time_x) % gcd_final != 0:
            continue

        step_multiplier = (inv_cycle_x * ((time_y - time_x) // gcd_final)) % (cycle_y // gcd_final)
        total_steps = time_x + step_multiplier * cycle_x
        full_loop_period = (cycle_x * cycle_y) // gcd_final

        calculated_time = total_steps if total_steps > 0 else full_loop_period

        if calculated_time < earliest_hit_time:
            earliest_hit_time = calculated_time
            best_asteroid_index = i

    return best_asteroid_index

def main():
    test_case_count = int(input())
    for _ in range(test_case_count):
        header = input().split()
        num_asteroids = int(header[0])
        grid_n = int(header[1])
        grid_m = int(header[2])
        jump_p = int(header[3])
        jump_q = int(header[4])

        asteroid_x = []
        asteroid_y = []
        for _ in range(num_asteroids):
            coordinates = input().split()
            asteroid_x.append(int(coordinates[0]))
            asteroid_y.append(int(coordinates[1]))

        print(solve(num_asteroids, grid_n, grid_m, jump_p, jump_q, asteroid_x, asteroid_y))

if __name__ == '__main__':
    main()