# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVhucHNsCmw85k_q8GSRZjqbUjvvD5NC
"""

import sys

def solve():
    # Read all inputs from standard input fast
    input_data = sys.stdin.read().split()
    if not input_data:
        return

    T = int(input_data)
    idx = 1

    out = []

    for _ in range(T):
        N = int(input_data[idx])
        M = int(input_data[idx+1])
        idx += 2

        # Precompute the 5 possible row patterns for the current width M
        # This dramatically speeds up execution for large grids (e.g., 1000x1000)
        base_rows = []
        for r in range(5):
            # Applying the mathematical formula: (r + 2c) % 5
            row_vals = [str((r + 2 * c) % 5) for c in range(M)]
            base_rows.append(" ".join(row_vals))

        # Build the final grid for this testcase using the repeating row patterns
        for r in range(N):
            out.append(base_rows[r % 5])

    # Print everything at once for maximum I/O performance
    sys.stdout.write('\n'.join(out) + '\n')

if __name__ == '__main__':
    solve()