# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVhucHNsCmw85k_q8GSRZjqbUjvvD5NC
"""

import sys

def _generate_patterned_grid_rows(N, M):
    """Generates N rows for a grid of width M based on the (r + 2c) % 5 pattern."""
    base_patterns = []
    # Precompute the 5 possible row patterns for the current width M
    for r_pattern_index in range(5):
        # Applying the mathematical formula: (r_pattern_index + 2c) % 5
        row_values = [str((r_pattern_index + 2 * col_index) % 5) for col_index in range(M)]
        base_patterns.append(" ".join(row_values))

    # Build the final grid rows using the repeating row patterns
    grid_rows = []
    for row_num in range(N):
        grid_rows.append(base_patterns[row_num % 5])
    return grid_rows

def solve():
    # Read all inputs from standard input fast
    input_data = sys.stdin.read().split()
    if not input_data:
        return

    # Correctly read T from the first element of input_data
    T = int(input_data[0])
    # Initialize idx to 1, as input_data[0] is T, and N, M pairs start from input_data[1]
    idx = 1

    output_lines = []

    for _ in range(T):
        N = int(input_data[idx])
        M = int(input_data[idx+1])
        idx += 2

        current_testcase_rows = _generate_patterned_grid_rows(N, M)
        output_lines.extend(current_testcase_rows)

    # Print everything at once for maximum I/O performance
    sys.stdout.write('\n'.join(output_lines) + '\n')

if __name__ == '__main__':
    solve()