# -*- coding: utf-8 -*-
"""answers_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qqssl8gMuP4g_mNKXuIeq3JsdePkwJYT
"""

P, N=map(int, input().split())
E=list(map(int, input().split()))
R, K=map(int, input().split())

current_power = P
curses_defeated_count = 0
outcome = "nah i’d win"

for i in range(N):
    current_power -= E[i]
    curses_defeated_count += 1

    if current_power < 0:
        outcome = "nah i’d lose"
        break

    if curses_defeated_count % K == 0:
        current_power += R

print(outcome)

dylan_power = 9001