# -*- coding: utf-8 -*-
"""4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjFDneEML1I6rBIAtnicWyR_f6qMNB1U
"""

from fractions import Fraction

def solve(N, M, factory):
    """
    Simulate the factory and return the final output as the fraction P / Q.
    """
    directions = {
        '^': (-1, 0),
        'v': (1, 0),
        '<': (0, -1),
        '>': (0, 1),
    }

    def in_bounds(r, c):
        return 0 <= r < N and 0 <= c < M

    def outgoing_edges(r, c):
        cell = factory[r][c]
        if cell in directions:
            dr, dc = directions[cell]
            return [((r + dr, c + dc), Fraction(1))]

        if cell == 's' or cell == 'S':
            neighbors = []
            for dr, dc in directions.values():
                nr, nc = r + dr, c + dc
                if not in_bounds(nr, nc):
                    continue
                adj_tile = factory[nr][nc]
                if adj_tile == 'x' or adj_tile == 'X':
                    neighbors.append((nr, nc))
                elif adj_tile in directions:
                    adr, adc = directions[adj_tile]
                    if (nr + adr, nc + adc) != (r, c):
                        neighbors.append((nr, nc))

            if not neighbors:
                return []
            weight = Fraction(1, len(neighbors))
            return [(pos, weight) for pos in neighbors]

        return []

    memo = {}

    def evaluate(r, c):
        if not in_bounds(r, c):
            return Fraction(1)

        if (r, c) in memo:
            return memo[(r, c)]

        cell_value = factory[r][c]
        if cell_value == '.' or cell_value == 'x' or cell_value == 'X':
            memo[(r, c)] = Fraction(0)
            return Fraction(0)

        edges = outgoing_edges(r, c)
        if not edges:
            memo[(r, c)] = Fraction(0)
            return Fraction(0)

        total = Fraction(0)
        for (nr, nc), weight in edges:
            total += weight * evaluate(nr, nc)

        memo[(r, c)] = total
        return total

    result = evaluate(0, 0)
    return result.numerator, result.denominator

def main():
    T_cases = int(input().strip())
    for _ in range(T_cases):
        N, M = map(int, input().split())
        factory = [input().strip() for _ in range(N)]
        P, Q = solve(N, M, factory)
        print(f"{P} {Q}")

if __name__ == '__main__':
    main()