# -*- coding: utf-8 -*-
"""problem-12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9PLfUi4epMmVUgdYUr6I8JYpJjyqohr

**Rank_3+4+4**

Problem-12
"""

def solve(N, M, D, cells):
    import math

    arr = [1] * N

    for r, c, v, w in cells:
        ri, ci = r - 1, c - 1
        guess = max(1, int(math.sqrt(v)))
        if arr[ri] == 1:
            arr[ri] = guess
        if arr[ci] == 1:
            arr[ci] = guess

    for _ in range(30):
        better = False

        for i in range(N):
            old_val = arr[i]
            old_cost = calc_cost(arr, cells)

            for try_val in range(max(1, arr[i] - 2), min(1000000000, arr[i] + 3)):
                arr[i] = try_val
                new_cost = calc_cost(arr, cells)

                if new_cost < old_cost:
                    old_cost = new_cost
                    old_val = try_val
                    better = True

            arr[i] = old_val

        if not better:
            break

    bad_ones = []
    for idx, (r, c, v, w) in enumerate(cells):
        ri, ci = r - 1, c - 1
        actual = arr[ri] * arr[ci]
        diff = abs(actual - v) / v
        score = w * diff
        bad_ones.append((score, idx + 1))

    bad_ones.sort()
    bad_ones.reverse()

    throw_away = []
    for i in range(min(D, len(bad_ones))):
        if bad_ones[i][0] > 0:
            throw_away.append(bad_ones[i][1])

    return arr, throw_away

def calc_cost(arr, cells):
    total = 0
    for r, c, v, w in cells:
        ri, ci = r - 1, c - 1
        actual = arr[ri] * arr[ci]
        err = abs(actual - v) / v
        total += w * err
    return total

def main():
    N, M, D = map(int, input().split())
    cells = []
    for _ in range(M):
        R, C, V, W = map(int, input().split())
        cells.append((R, C, V, W))
    A, discards = solve(N, M, D, cells)
    print(' '.join(str(x) for x in A))
    print(' '.join(str(x) for x in [len(discards)] + list(discards)))

if __name__ == '__main__':
    main()

