# -*- coding: utf-8 -*-
"""Calico prob no 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HQVtakZG3sn9XCNoRMO21n8p5gWQtLh0
"""

import sys

def solve():
    data = sys.stdin.read().split()
    if not data:
        return

    t_cases = int(data[0])
    ptr = 1
    results = []

    for _ in range(t_cases):
        A = data[ptr]
        B = data[ptr+1]
        ptr += 2

        b_idx = 0
        b_len = len(B)
        dylan_power = []

        # greedy match characters of B in A
        for char in A:
            if b_idx < b_len and char == B[b_idx]:
                dylan_power.append(char)
                b_idx += 1
            else:
                dylan_power.append('#')

        results.append("".join(dylan_power))

    sys.stdout.write("\n".join(results) + "\n")

def read_your_input():
    solve()

if __name__ == '__main__':
    read_your_input()