# -*- coding: utf-8 -*-
"""problem-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9PLfUi4epMmVUgdYUr6I8JYpJjyqohr

**Rank_1**

Problem-3 = The Big Ben Files
"""

def solve(A: str, B: str) -> str:
    j = 0
    res = ""
    for c in A:
        if j < len(B) and c == B[j]:
            res += c
            j += 1
        else:
            res += "#"
    return res

def main():
    T = int(input())
    for _ in range(T):
        A = input()
        B = input()
        print(solve(A, B))

if __name__ == '__main__':
    main()

