# -*- coding: utf-8 -*-
"""Problem9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSw4W9tMj7LwdPYQ-lpLigBcQaMzRZ-T
"""

from math import gcd
from collections import deque

def solve_factory(grid):
    n, m = len(grid), len(grid[0])
    dirs = {'^': (-1, 0), 'v': (1, 0), '<': (0, -1), '>': (0, 1)}

    def valid_neighbors(r, c):
        ch = grid[r][c]

        if ch in dirs:
            dr, dc = dirs[ch]
            nr, nc = r + dr, c + dc
            return [(nr, nc)] if 0 <= nr < n and 0 <= nc < m else []

        elif ch == 'S':
            res = []
            for dr, dc in dirs.values():
                nr, nc = r + dr, c + dc
                if 0 <= nr < n and 0 <= nc < m:
                    nxt = grid[nr][nc]

                    if nxt == 'X':
                        res.append((nr, nc))

                    elif nxt in dirs:
                        back_dr, back_dc = dirs[nxt]
                        if (nr + back_dr, nc + back_dc) != (r, c):
                            res.append((nr, nc))
            return res

        return []

    frac = [[(0, 1) for _ in range(m)] for _ in range(n)]
    frac[0][0] = (1, 1)

    def add_frac(a, b):
        an, ad = a
        bn, bd = b
        num = an * bd + bn * ad
        den = ad * bd
        g = gcd(num, den)
        return num // g, den // g

    q = deque([(0, 0)])
    seen = [[False] * m for _ in range(n)]
    seen[0][0] = True

    collected = (0, 1)

    while q:
        r, c = q.popleft()
        num, den = frac[r][c]

        if num == 0:
            continue

        ch = grid[r][c]

        if ch == 'X':
            continue

        elif ch in dirs:
            dr, dc = dirs[ch]
            nr, nc = r + dr, c + dc

            if 0 <= nr < n and 0 <= nc < m:
                frac[nr][nc] = add_frac(frac[nr][nc], (num, den))
                if not seen[nr][nc]:
                    seen[nr][nc] = True
                    q.append((nr, nc))
            else:
                collected = add_frac(collected, (num, den))

        elif ch == 'S':
            neighbors = valid_neighbors(r, c)

            if neighbors:
                share_den = den * len(neighbors)
                share_num = num
                g = gcd(share_num, share_den)
                share = (share_num // g, share_den // g)

                for nr, nc in neighbors:
                    frac[nr][nc] = add_frac(frac[nr][nc], share)
                    if not seen[nr][nc]:
                        seen[nr][nc] = True
                        q.append((nr, nc))
    p, qv = collected
    g = gcd(p, qv)
    return p // g, qv // g
t = 1
tests = [
    (
        3, 3,
        [
            ">..",
            ".^.",
            ".X<"
        ]
    )
]
for n, m, grid in tests:
    p, q = solve_factory(grid)
    print(f"{p} {q}")