# -*- coding: utf-8 -*-
"""q8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYNyYyH6dCkDBEStNlYvx75UUvyYxQPT
"""

import sys

sample_input_data = [
    "5",
    "0 0 0 1",
    "0 0 -1 -4",
    "1 3 3 8",
    "0 -6 7 0",
    "-10 -10 10 10"
]
input_iter = iter(sample_input_data)
def mock_input():
    return next(input_iter) + "\n"

input = mock_input

def solve():
    t = int(input())

    create_voronoi_7 = 0

    for _ in range(t):
        xg, yg, xm, ym = map(int, input().split())

        dx = abs(xg - xm)
        dy = abs(yg - ym)

        d = dx + dy

        k = (2 * d - 1) // 5

        if k < 0:
            print(0)
            continue


        ans = 1 + 2 * k * (k + 1)

        print(ans)

def read_your_input():
    solve()

if __name__ == "__main__":
    read_your_input()

