# -*- coding: utf-8 -*-
"""question8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYNyYyH6dCkDBEStNlYvx75UUvyYxQPT
"""

def solve():
    import sys

    sample_input_data = [
        "5",
        "0 0 0 1",
        "0 0 -1 -4",
        "1 3 3 8",
        "0 -6 7 0",
        "-10 -10 10 10"
    ]

    input_data = iter(sample_input_data)
    input = lambda: next(input_data)

    t = int(input())

    create_voronoi_7 = 0

    for _ in range(t):
        xg, yg, xm, ym = map(int, input().split())

        dx = abs(xg - xm)
        dy = abs(yg - ym)
        d = dx + dy

        ans = 0


        limit = d * 2 + 10

        for x in range(-limit, limit + 1):


            rhs = 2 * abs(x - d) - 7 * abs(x)

            if rhs <= 0:
                continue

            max_y = (rhs - 1) // 5
            ans += 2 * max_y + 1

        print(ans)

def read_your_input():
    solve()

if __name__ == "__main__":
    read_your_input()

