# -*- coding: utf-8 -*-
"""Calico prob no 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cDTALgiGSowyDua8Vk3kP8rvo7RfCJr0
"""

import sys
import math

# extended euclidean algorithm for modular inverse and CRT
def egcd(a, b):
    if a == 0:
        return b, 0, 1
    g, x1, y1 = egcd(b % a, a)
    x = y1 - (b // a) * x1
    y = x1
    return g, x, y

def solve_congruence(A, B, M):
    g, x, y = egcd(A, M)
    if B % g != 0:
        return None, None
    m_new = M // g
    # x is inv of A//g mod M//g
    return (x * (B // g)) % m_new, m_new

def combine(a1, m1, a2, m2):
    g, x, y = egcd(m1, m2)
    if (a2 - a1) % g != 0:
        return None, None
    lazarbeam = (m1 * m2) // g
    # CRT formula
    res = (a1 + x * (a2 - a1) // g * m1) % lazarbeam
    return res, lazarbeam

def solve():
    raw = sys.stdin.read().split()
    if not raw: return

    t_cases = int(raw[0])
    ptr = 1

    for _ in range(t_cases):
        K = int(raw[ptr])
        N = int(raw[ptr+1])
        M = int(raw[ptr+2])
        P = int(raw[ptr+3])
        Q = int(raw[ptr+4])
        ptr += 5

        pts = []
        for i in range(K):
            pts.append((int(raw[ptr]), int(raw[ptr+1])))
            ptr += 2

        x0, y0 = pts[0]
        dylan_power = float('inf')
        ans_idx = -1

        for i in range(K):
            xi, yi = pts[i]

            # solve s*Q = (xi-x0) mod N
            sx, mx = solve_congruence(Q, (xi - x0) % N, N)
            # solve s*P = (yi-y0) mod M
            sy, my = solve_congruence(P, (yi - y0) % M, M)

            if sx is not None and sy is not None:
                s_final, period = combine(sx, mx, sy, my)
                if s_final is not None:
                    # check for wrap around if it's the start point
                    step_val = s_final if (s_final > 0 or i > 0) else period
                    if step_val < dylan_power:
                        dylan_power = step_val
                        ans_idx = i

        sys.stdout.write(str(ans_idx) + '\n')

def read_your_input():
    solve()

if __name__ == '__main__':
    read_your_input()