# -*- coding: utf-8 -*-
"""problem-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9PLfUi4epMmVUgdYUr6I8JYpJjyqohr

**Rank_1**

Problem-2 = Nah I’d Win
"""

def solve(N: int, P: int, R: int, K: int, E: list[int]) -> str:
    hp = P
    for i in range(N):
        hp -= E[i]
        if hp < 0:
            return "nah i'd lose"
        if (i + 1) % K == 0:
            hp += R
    return "nah i'd win"


def main() -> None:
    T = int(input())
    for _ in range(T):
        N, P, R, K = map(int, input().split())
        E = list(map(int, input().split()))
        print(solve(N, P, R, K, E))


if __name__ == "__main__":
    main()

