# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVhucHNsCmw85k_q8GSRZjqbUjvvD5NC
"""

import sys
input = sys.stdin.readline

def ext_gcd(a, b):
    if b == 0:
        return a, 1, 0
    g, x, y = ext_gcd(b, a % b)
    return g, y, x - (a // b) * y

def solve_linear_congruence(a, b, m):
    # solve a*t ≡ b (mod m), returns (t0, mod) or None
    g, x, _ = ext_gcd(a % m, m)
    if b % g != 0:
        return None
    m2 = m // g
    t0 = (x * (b // g)) % m2
    return (t0, m2)

def crt(r1, m1, r2, m2):
    # solve t ≡ r1 (mod m1), t ≡ r2 (mod m2)
    g, p, _ = ext_gcd(m1, m2)
    if (r2 - r1) % g != 0:
        return None
    lcm = m1 // g * m2
    t0 = (r1 + m1 * ((p * ((r2 - r1) // g)) % (m2 // g))) % lcm
    return (t0, lcm)

def laser(K, N, M, P, Q, asteroids):
    x0, y0 = asteroids[0]
    asteroid_set = {}
    for i in range(1, K):
        xi, yi = asteroids[i]
        key = (xi, yi)
        if key not in asteroid_set:
            asteroid_set[key] = i

    best_t = -1
    best_idx = -1

    for i in range(1, K):
        xi, yi = asteroids[i]
        dx = (xi - x0) % N
        dy = (yi - y0) % M

        # t*Q ≡ dx (mod N)
        res_x = solve_linear_congruence(Q, dx, N)
        if res_x is None:
            continue
        tx, mx = res_x

        # t*P ≡ dy (mod M)
        res_y = solve_linear_congruence(P, dy, M)
        if res_y is None:
            continue
        ty, my = res_y

        # combine: t ≡ tx (mod mx), t ≡ ty (mod my)
        res = crt(tx, mx, ty, my)
        if res is None:
            continue
        t0, mod = res
        if t0 == 0:
            t0 = mod  # must be t > 0

        if best_t == -1 or t0 < best_t:
            best_t = t0
            best_idx = i

    # Also check if asteroid 0 can be revisited (wrap around)
    # t*Q ≡ 0 (mod N) and t*P ≡ 0 (mod M), t > 0
    res_x = solve_linear_congruence(Q, 0, N)
    res_y = solve_linear_congruence(P, 0, M)
    if res_x is not None and res_y is not None:
        tx, mx = res_x
        ty, my = res_y
        res = crt(tx, mx, ty, my)
        if res is not None:
            t0, mod = res
            if t0 == 0:
                t0 = mod
            if best_t == -1 or t0 < best_t:
                best_t = t0
                best_idx = 0

    return best_idx

def main():
    T = int(input())
    for _ in range(T):
        line = input().split()
        K, N, M, P, Q = int(line[0]), int(line[1]), int(line[2]), int(line[3]), int(line[4])
        asteroids = []
        for _ in range(K):
            x, y = map(int, input().split())
            asteroids.append((x, y))
        print(laser(K, N, M, P, Q, asteroids))

main()