# -*- coding: utf-8 -*-
"""q3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYNyYyH6dCkDBEStNlYvx75UUvyYxQPT
"""

def censor_this_please(A, B):
    j = 0
    result = []

    for i in range(len(A)):
        if j < len(B) and A[i] == B[j]:
            result.append(A[i])
            j += 1
        else:
            result.append('#')

    return ''.join(result)


sample_input_data = [
    "5",
    "ccaalliiccoo",
    "calico",
    "big_bens_bday",
    "bbb",
    "job",
    "jb",
    "include_over_californication",
    "ilovecalico",
    "six_seven_rizzler_sigma_banned_discord_skibidi_toilet",
    "severance"
]
input_iter = iter(sample_input_data)
def mock_input():
    return next(input_iter) + "\n"

input = mock_input

t = int(input())
for _ in range(t):
    A = input().strip()
    B = input().strip()
    print(censor_this_please(A, B))

