# -*- coding: utf-8 -*-
"""Calico prob no 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19953pcdExeFj98uN-P0TzhM2MVGtcKqF
"""

import sys

def solve():
    data = sys.stdin.read().split()
    if not data:
        return

    T_cases = int(data[0])
    ptr = 1

    results = []
    for _ in range(T_cases):
        N = int(data[ptr])
        P = int(data[ptr+1])
        R = int(data[ptr+2])
        K = int(data[ptr+3])
        ptr += 4

        curses = data[ptr:ptr+N]
        ptr += N

        dylan_power = P
        possible = True

        for i in range(N):
            dylan_power -= int(curses[i])

            if dylan_power < 0:
                possible = False
                break

            if (i + 1) % K == 0:
                dylan_power += R

        results.append("nah i'd win" if possible else "nah i'd lose")

    sys.stdout.write('\n'.join(results) + '\n')

def read_your_input():
    solve()

if __name__ == '__main__':
    read_your_input()