# -*- coding: utf-8 -*-
"""problem2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oTIHSnxBCrKwHFpuzZe5-r3iFP3w765Z
"""

import sys
import io

# Simulate input for testing purposes
# Replace this with actual input when running in a contest or with a specific input file
_TEST_INPUT = """6
5 60 5 1
12 6 23 8 10
4 42 10 3
40 10 5 8
3 10 5 2
5 5 5
3 20 50 3
10 10 10
4 5 10 1
4 10 10 10
1 10 100 1
15"""
sys.stdin = io.StringIO(_TEST_INPUT)

input = sys.stdin.readline

dylan_power = 0

t = int(input())
for _ in range(t):
    n, p, r, k = map(int, input().split())
    e = list(map(int, input().split()))

    power = p
    count = 0
    win = True

    for i in range(n):
        if power < e[i]:
            if count >= k:
                power += r
                count = 0
            if power < e[i]:
                win = False
                break

        power -= e[i]
        count += 1

        if count == k:
            power += r
            count = 0

    print("nah i’d win" if win else "nah i’d lose")

# To restore original stdin uncomment the line below if other parts of the notebook rely on it.
# sys.stdin = sys.__stdin__

