# -*- coding: utf-8 -*-
"""Problem10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSw4W9tMj7LwdPYQ-lpLigBcQaMzRZ-T
"""

import sys

def read_your_input():
    return sys.stdin.readline().strip()

def solve():
    data = sys.stdin.read().strip().split()
    if not data:
        return

    T = int(data[0])
    idx = 1
    out = []

    for _ in range(T):
        P = int(data[idx])
        A = int(data[idx+1])
        B = int(data[idx+2])
        idx += 3

        N = 1 + A + B
        M = 3

        grid = []
        grid.append(list("S>>"))

        for i in range(A):
            grid.append(list("S>>"))
        for i in range(B):
            grid.append(list("S>>"))
        last_row = []
        for j in range(M):
            if j < P % M:
                last_row.append(">")
            else:
                last_row.append("X")
        grid.append(last_row)

        if N * M > 2000:
            grid = [["X"]]
            N, M = 1, 1

        out.append(f"{N} {M}")
        out.extend("".join(row) for row in grid)

    sys.stdout.write("\n".join(out))

if __name__ == "__main__":
    solve()