# -*- coding: utf-8 -*-
"""P2new .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCaSV46gDWz5Iyic1W3JmWyqjGmpA16G
"""

def solve():
    t = int(input().strip())

    for _ in range(t):
        n, p, r, k = map(int, input().split())
        E = list(map(int, input().split()))

        defeat = 0
        used = 0
        poss = True

        for i in range(n):

            while p < E[i]:
                available = (defeat // k) - used

                if available > 0:
                    p += r
                    used += 1
                else:
                    poss = False
                    break

            if not poss:
                break

            p -= E[i]
            defeat += 1

        if poss:
            print("nah i'd win")
        else:
            print("nah i'd lose")


if __name__ == "__main__":
    solve()