# -*- coding: utf-8 -*-
"""shadows.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjFDneEML1I6rBIAtnicWyR_f6qMNB1U
"""

def solve(N: int, S1: list[str], S2: list[str]) -> tuple[int, int]:
    max_volume = 0
    min_volume = 0

    for row1, row2 in zip(S1, S2):
        r1 = row1.count('#')
        r2 = row2.count('#')

        if r1 > 0 and r2 > 0:
            max_volume += r1 * r2
            min_volume += max(r1, r2)

    return max_volume, min_volume

def main():
    line = input().strip()
    if not line:
        return
    T = int(line)

    for _ in range(T):
        N_line = input().strip()
        if not N_line:
            continue
        N = int(N_line)

        S1 = [input().strip() for _ in range(N)]
        S2 = [input().strip() for _ in range(N)]

        result = solve(N, S1, S2)
        print(f"{result[0]} {result[1]}")

if __name__ == '__main__':
    main()