# -*- coding: utf-8 -*-
"""q7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYNyYyH6dCkDBEStNlYvx75UUvyYxQPT
"""

pythonid="crissx92"
import sys

sample_input_data = [
    "2",
    "3 4",
    "2 2"
]
input_iter = iter(sample_input_data)
def mock_input():
    return next(input_iter)

input = mock_input

def make_the_criss_cross(n, m):
    grid = [[0]*m for _ in range(n)]

    for i in range(n):
        for j in range(m):
            grid[i][j] = (i + j) % 5

    return grid

def solve():
    t = int(input())
    for _ in range(t):
        n, m = map(int, input().split())
        grid = make_the_criss_cross(n, m)

        for row in grid:
            print(*row)

def read_your_input():
    solve()

if __name__ == "__main__":
    read_your_input()

