# -*- coding: utf-8 -*-
"""lecture_main_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7oKBA9xZS1Dr8mZU7GkDhRrTqVT0hOa
"""

import sys
import io

# 🔹 Inject your test input here
input_data = """3
3 3 2
#--
-##
##-
5 4 5
--##
#--#
####
#-##
#-##
2 7 2
#-#--##
#-#####
"""

sys.stdin = io.StringIO(input_data)

input = sys.stdin.readline


def solve():
    T = int(input())
    for _ in range(T):
        N, M, K = map(int, input().split())
        grid = [input().strip() for _ in range(N)]

        seats = []
        for r in range(N):
            for c in range(M):
                if grid[r][c] == '-':
                    seats.append((r, c))

        # SIMPLE VALID STRATEGY:
        # pick first K available seats
        for i in range(K):
            print(seats[i][0], seats[i][1])


if __name__ == "__main__":
    solve()