# -*- coding: utf-8 -*-
"""lecture_main_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7oKBA9xZS1Dr8mZU7GkDhRrTqVT0hOa
"""

import sys
import io

# 🔷 MOCK INPUT
sys.stdin = io.StringIO("""3
3 3 2
#--
-##
##-
5 4 5
--##
#--#
####
#-##
#-##
2 7 2
#-#--##
#-#####
""")

input = sys.stdin.readline

# 🔷 AURA COMPUTATION
def compute_aura(grid, N, M):
    aura = [[0]*M for _ in range(N)]
    for r in range(N):
        left = [0]*M
        right = [0]*M

        cnt = 0
        for c in range(M):
            left[c] = cnt
            if grid[r][c] == '#':
                cnt += 1

        cnt = 0
        for c in range(M-1, -1, -1):
            right[c] = cnt
            if grid[r][c] == '#':
                cnt += 1

        for c in range(M):
            aura[r][c] = min(left[c], right[c])
    return aura


# 🔷 SOLUTION (BONUS-safe)
def solve():
    T = int(input())
    for _ in range(T):
        N, M, K = map(int, input().split())
        grid = [input().strip() for _ in range(N)]

        aura = compute_aura(grid, N, M)

        points = []
        for r in range(N):
            for c in range(M):
                if grid[r][c] == '-':
                    points.append((aura[r][c], r, c))

        # pick smallest aura K seats
        points.sort()

        for i in range(K):
            print(points[i][1], points[i][2])


# 🔷 RUN
solve()

