# -*- coding: utf-8 -*-
"""lecture_main_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7oKBA9xZS1Dr8mZU7GkDhRrTqVT0hOa
"""

import sys
import io

sys.stdin = io.StringIO("""3
3 3 2
#--
-##
##-
5 4 5
--##
#--#
####
#-##
#-##
2 7 2
#-#--##
#-#####
""")

input = sys.stdin.readline


def compute_aura(grid, N, M):
    aura = [[0]*M for _ in range(N)]
    for r in range(N):
        left = [0]*M
        right = [0]*M

        cnt = 0
        for c in range(M):
            left[c] = cnt
            if grid[r][c] == '#':
                cnt += 1

        cnt = 0
        for c in range(M-1, -1, -1):
            right[c] = cnt
            if grid[r][c] == '#':
                cnt += 1

        for c in range(M):
            aura[r][c] = min(left[c], right[c])
    return aura



def feasible(points, K, D):
    n = len(points)
    j = 0
    v_vals = []

    for i in range(n):
        while j < n and points[j][0] - points[i][0] <= D:
            v_vals.append(points[j][1])
            j += 1

        v_vals.sort()

        l = 0
        for r in range(len(v_vals)):
            while v_vals[r] - v_vals[l] > D:
                l += 1
            if r - l + 1 >= K:
                return True

        if points[i][1] in v_vals:
            v_vals.remove(points[i][1])

    return False



def build(points, K, D):
    n = len(points)
    j = 0
    window = []

    for i in range(n):
        while j < n and points[j][0] - points[i][0] <= D:
            window.append(points[j])
            j += 1

        window.sort(key=lambda x: x[1])

        l = 0
        for r in range(len(window)):
            while window[r][1] - window[l][1] > D:
                l += 1
            if r - l + 1 >= K:
                candidates = window[l:r+1]
                candidates.sort(key=lambda x: x[4])  # minimize aura
                return candidates[:K]

        if points[i] in window:
            window.remove(points[i])

    return []


def solve():
    T = int(input())
    for _ in range(T):
        N, M, K = map(int, input().split())
        grid = [input().strip() for _ in range(N)]

        aura = compute_aura(grid, N, M)

        points = []
        for r in range(N):
            for c in range(M):
                if grid[r][c] == '-':
                    u = r + c
                    v = r - c
                    points.append((u, v, r, c, aura[r][c]))

        points.sort()

        lo, hi = 0, 2*(N+M)
        ans = hi

        while lo <= hi:
            mid = (lo + hi)//2
            if feasible(points, K, mid):
                ans = mid
                hi = mid - 1
            else:
                lo = mid + 1

        res = build(points, K, ans)

        for p in res:
            print(p[2], p[3])


solve()

