# -*- coding: utf-8 -*-
"""problem-6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9PLfUi4epMmVUgdYUr6I8JYpJjyqohr

**Rank_2**

Problem-6
"""

def solve(N: int, S1: list[str], S2: list[str]) -> tuple[int, int]:

    max_vol = 0
    for x in range(N):
        for y in range(N):
            for z in range(N):
                if S1[x][y] == '#' and S2[x][z] == '#':
                    max_vol += 1

    s1_pos = set()
    s2_pos = set()

    for x in range(N):
        for y in range(N):
            if S1[x][y] == '#':
                s1_pos.add((x, y))

    for x in range(N):
        for z in range(N):
            if S2[x][z] == '#':
                s2_pos.add((x, z))

    if not s1_pos and not s2_pos:
        return max_vol, 0

    blocks = set()

    for x, y in s1_pos:
        best_z = None
        for z in range(N):
            if (x, z) in s2_pos:
                best_z = z
                break

        if best_z is not None:
            blocks.add((x, y, best_z))
        else:
            blocks.add((x, y, 0))

    for x, z in s2_pos:
        covered = False
        for y in range(N):
            if (x, y, z) in blocks:
                covered = True
                break

        if not covered:

            best_y = None
            for y in range(N):
                if (x, y) in s1_pos:
                    best_y = y
                    break

            if best_y is not None:
                blocks.add((x, best_y, z))
            else:
                blocks.add((x, 0, z))

    return max_vol, len(blocks)


def main():
    T = int(input())
    for _ in range(T):
        N = int(input())
        S1 = [input() for _ in range(N)]
        S2 = [input() for _ in range(N)]
        print(*solve(N, S1, S2))


if __name__ == '__main__':
    main()

