# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ElEq-T4-0nC3hPU62jZalk3jXyeb1NbY
"""

def destroy_the_tiles():
    pass

def solve(P, A, B):
    blocks = []

    curr_p = P
    a_count = A
    b_count = B

    while a_count > 0:
        remainder = curr_p % 2
        curr_p //= 2
        a_count -= 1
        if remainder == 1:
            blocks.append("..S>>")
        else:
            blocks.append("..SX.")

    while b_count > 0:
        remainder = curr_p % 3
        curr_p //= 3
        b_count -= 1
        if remainder == 2:
            blocks.append("<<S>>")
        elif remainder == 1:
            blocks.append("<<SX.")
        else:
            blocks.append(".XSX.")

    blocks.reverse()

    ans = []
    ans.append(">>v..")

    for b in blocks:
        ans.append("..v..")
        ans.append(b)

    ans.append("..X..")

    return ans

def main():
    import sys
    input = sys.stdin.read
    data = input().split()
    if not data:
        return

    T = int(data[0])
    index = 1

    for _ in range(T):
        P = int(data[index])
        A = int(data[index+1])
        B = int(data[index+2])
        index += 3

        factory = solve(P, A, B)
        N = len(factory)
        M = len(factory[0])

        print(f"{N} {M}")
        for row in factory:
            print(row)

def read_your_input():
    pass

if __name__ == '__main__':
    main()