# -*- coding: utf-8 -*-
"""nah_Prob.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S8mDc1r4SpLdR6hINx6DSliiZHLkgyZ9
"""

def solve(N: int, P: int, R: int, K: int, E: list[int]) -> str:
    """
    Output whether Gojo will win the fight.

    N: Number of curses
    P: Gojo's starting power
    R: Amount of power Gojo can restore with Reverse Cursed Technique
    K: The cooldown of Reverse Cursed Technique
    E: List of power levels of curses
    """
    # YOUR CODE HERE
    #loop
    for i in range(N):

        #subtract powers from the curses
        Rem_P = P = P - E[i]


        #nah i’d lose
        if P < 0:
            return "nah i’d lose"


        #nah i’d win
        if (i + 1) % K == 0:
            P += R

    return "nah i’d win"




def main() -> None:
    T = int(input())
    for _ in range(T):
        N, P, R, K = map(int, input().split())
        E = list(map(int, input().split()))
        print(solve(N, P, R, K, E))


if __name__ == "__main__":
    main()