# -*- coding: utf-8 -*-
"""Calico question 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTx4IrlKRBqxTiEhWkslTCd0GIXc3leN
"""

def solve():
    T = int(input("Enter number of test cases: "))

    for i in range(T):
        N, P, R, K = map(int, input("Enter value of N, P, R, K: ").split())
        E = list(map(int, input("Damage dealt by each enemy: ").split()))

        dylan_power = P

        for j in range(N):
            dylan_power = dylan_power - E[j]

            if dylan_power < 0:
                print("nah i'd lose")
                break

            if (j + 1) % K == 0:
                dylan_power = dylan_power + R
        else:
            print("nah i'd win")
    pass

if __name__ == "__main__":
    solve()

