# -*- coding: utf-8 -*-
"""problem-8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9PLfUi4epMmVUgdYUr6I8JYpJjyqohr

Problem-7

Rank: 2+3+3+4
"""

def solve(X_G: int, Y_G: int, X_M: int, Y_M: int) -> int:
    grass_tiles = {(X_G, Y_G)}
    mycel_tiles = {(X_M, Y_M)}
    all_mycel = {(X_M, Y_M)}

    tick = 1
    max_ticks = 2000

    while tick <= max_ticks:
        new_grass = set()
        new_mycel = set()

        if tick % 2 == 0:
            for x, y in grass_tiles:
                for dx, dy in [(0,1), (0,-1), (1,0), (-1,0)]:
                    nx, ny = x + dx, y + dy
                    if (nx, ny) not in grass_tiles and (nx, ny) not in mycel_tiles:
                        new_grass.add((nx, ny))

        if tick % 7 == 0:
            for x, y in mycel_tiles:
                for dx, dy in [(0,1), (0,-1), (1,0), (-1,0)]:
                    nx, ny = x + dx, y + dy
                    if (nx, ny) not in grass_tiles and (nx, ny) not in mycel_tiles:
                        new_mycel.add((nx, ny))

        overlap = new_grass & new_mycel
        new_mycel -= overlap

        grass_tiles.update(new_grass)
        mycel_tiles.update(new_mycel)
        all_mycel.update(new_mycel)

        if not new_mycel and tick % 7 == 0:
            break

        tick += 1

    return len(all_mycel)


def main():
    T = int(input())
    for _ in range(T):
        X_G, Y_G, X_M, Y_M = map(int, input().split())
        print(solve(X_G, Y_G, X_M, Y_M))


if __name__ == '__main__':
    main()

