# -*- coding: utf-8 -*-
"""problem-7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9PLfUi4epMmVUgdYUr6I8JYpJjyqohr

Problem-7

Rank-2
"""

def solve(N, M):
    grid = [[0 for _ in range(M)] for _ in range(N)]

    for i in range(N):
        for j in range(M):
            grid[i][j] = (2 * i + 3 * j) % 5

    return grid


def main():
    T = int(input())
    for _ in range(T):
        temp = input().split()
        N = int(temp[0])
        M = int(temp[1])
        grid = solve(N, M)
        for row in grid:
            print(' '.join(str(x) for x in row))


if __name__ == '__main__':
    main()

