Python 3.13.12 (tags/v3.13.12:1cbe481, Feb  3 2026, 18:22:25) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> L=float(input("Enter length (L): "))
... W=float(input("Enter width (W): "))
... E=float(input("Enter total electricity needed (E): "))
... R=float(input("Enter electricity regenerated per step (R): "))
... 
... area=2*(L + W)
... 
... 
... electricity_per_lap=area*R
... 
... 
... laps=int(E/electricity_per_lap)
... 
