# -*- coding: utf-8 -*-
"""answers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHz1lSy7oH1pGr5j6iA-NJbEfIFUvUJB
"""

L=float(input("Enter length (L): "))
W=float(input("Enter width (W): "))
E=float(input("Enter total electricity needed (E): "))
R=float(input("Enter electricity regenerated per step (R): "))

area=2*(L + W)


electricity_per_lap=area*R


laps=int(E/electricity_per_lap)

print(f"The total number of steps you will need is: ", laps)