# -*- coding: utf-8 -*-
"""cross.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjFDneEML1I6rBIAtnicWyR_f6qMNB1U
"""

def make_the_criss_cross(N, M):
    return [[(2 * r + c) % 5 for c in range(M)] for r in range(N)]

def read_your_input():
    T = int(input())
    for _ in range(T):
        temp = input().split()
        N = int(temp[0])
        M = int(temp[1])
        grid = make_the_criss_cross(N, M)
        for row in grid:
            print(' '.join(str(x) for x in row))

read_your_input()