# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LkZ2SdiZNoTR1TUsFy1jP4vjD3c2o-8R
"""

import sys
input = sys.stdin.readline

def solve():
    t = int(input())
    for _ in range(t):
        n, m, k = map(int, input().split())
        grid = [input().strip() for _ in range(n)]

        seats = []
        for r in range(n):
            for c in range(m):
                if grid[r][c] == '-':
                    u = r + c
                    v = r - c
                    seats.append((u, v, r, c))

        # Precompute aura loss
        aura = [[0]*m for _ in range(n)]
        for r in range(n):
            left = 0
            for c in range(m):
                aura[r][c] = left
                if grid[r][c] == '#':
                    left += 1
            right = 0
            for c in range(m-1, -1, -1):
                aura[r][c] = min(aura[r][c], right)
                if grid[r][c] == '#':
                    right += 1

        seats.sort()  # sort by u

        def check(D):
            from collections import deque
            import bisect

            vs = []
            j = 0

            for i in range(len(seats)):
                while j < len(seats) and seats[j][0] - seats[i][0] <= D:
                    bisect.insort(vs, seats[j][1])
                    j += 1

                # Now vs contains window
                # Check if we can find K points with v range ≤ D
                for x in range(len(vs)):
                    y = x + k - 1
                    if y < len(vs) and vs[y] - vs[x] <= D:
                        return True

                # Remove seats[i]
                idx = bisect.bisect_left(vs, seats[i][1])
                vs.pop(idx)

            return False

        # Binary search
        lo, hi = 0, 2*(n+m)
        ans = hi

        while lo <= hi:
            mid = (lo + hi) // 2
            if check(mid):
                ans = mid
                hi = mid - 1
            else:
                lo = mid + 1

        # Recover solution
        from collections import defaultdict
        import bisect

        vs = []
        j = 0
        result = []

        for i in range(len(seats)):
            while j < len(seats) and seats[j][0] - seats[i][0] <= ans:
                vs.append(seats[j])
                j += 1

            vs_sorted = sorted(vs, key=lambda x: x[1])

            for x in range(len(vs_sorted)):
                y = x + k - 1
                if y < len(vs_sorted) and vs_sorted[y][1] - vs_sorted[x][1] <= ans:
                    candidates = vs_sorted[x:y+1]

                    # Bonus: pick smallest aura sum
                    candidates.sort(key=lambda x: aura[x[2]][x[3]])
                    result = candidates[:k]
                    break

            if result:
                break

            # remove seats[i]
            for idx in range(len(vs)):
                if vs[idx] == seats[i]:
                    vs.pop(idx)
                    break

        for _, _, r, c in result:
            print(r, c)


if __name__ == "__main__":
    solve()