# -*- coding: utf-8 -*-
"""problem-9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9PLfUi4epMmVUgdYUr6I8JYpJjyqohr

**Rank_2**

Problem-9
"""

def solve(N, M, factory):
    from fractions import Fraction

    flow = {}
    flow[(0, 0)] = Fraction(1)

    for _ in range(1000):
        new_flow = {}

        for pos, amount in flow.items():
            if amount == 0:
                continue

            r, c = pos
            tile = factory[r][c]

            if tile == 'X':
                continue

            elif tile == '.':
                new_flow[pos] = new_flow.get(pos, Fraction(0)) + amount

            elif tile in '^v<>':
                if tile == '^':
                    nr, nc = r - 1, c
                elif tile == 'v':
                    nr, nc = r + 1, c
                elif tile == '<':
                    nr, nc = r, c - 1
                else:  # '>'
                    nr, nc = r, c + 1

                if 0 <= nr < N and 0 <= nc < M:
                    new_flow[(nr, nc)] = new_flow.get((nr, nc), Fraction(0)) + amount
                else:

                    new_flow[pos] = new_flow.get(pos, Fraction(0)) + amount

            elif tile == 'S':
                next_positions = []

                for dr, dc in [(-1,0), (1,0), (0,-1), (0,1)]:
                    nr, nc = r + dr, c + dc

                    if 0 <= nr < N and 0 <= nc < M:
                        neighbor = factory[nr][nc]

                        if neighbor == 'X':
                            next_positions.append((nr, nc))
                        elif neighbor in '^v<>':
                            if neighbor == '^' and nr - 1 == r and nc == c:
                                continue
                            elif neighbor == 'v' and nr + 1 == r and nc == c:
                                continue
                            elif neighbor == '<' and nr == r and nc - 1 == c:
                                continue
                            elif neighbor == '>' and nr == r and nc + 1 == c:
                                continue
                            else:
                                next_positions.append((nr, nc))

                if next_positions:
                    split_amount = amount / len(next_positions)
                    for nr, nc in next_positions:
                        new_flow[(nr, nc)] = new_flow.get((nr, nc), Fraction(0)) + split_amount

        if new_flow == flow:
            break
        flow = new_flow

    collected = Fraction(0)
    for pos, amount in flow.items():
        r, c = pos
        tile = factory[r][c]
        if tile in '^v<>' and amount > 0:
            if tile == '^':
                nr = r - 1
            elif tile == 'v':
                nr = r + 1
            elif tile == '<':
                nc = c - 1
            else:
                nc = c + 1

            if tile in '^v' and (nr < 0 or nr >= N):
                collected += amount
            elif tile in '<>' and (nc < 0 or nc >= M):
                collected += amount

    if collected == 0:
        return (0, 1)

    return (collected.numerator, collected.denominator)


def main():
    T = int(input())
    for _ in range(T):
        N, M = map(int, input().split())
        factory = [input() for _ in range(N)]
        P, Q = solve(N, M, factory)
        print(P, Q)


if __name__ == '__main__':
    main()

