# -*- coding: utf-8 -*-
"""Files.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/172LOkOKWHQeqlbzp0jEkJ4IOZYS7xNSe
"""

def solve(A: str, B: str) -> str:
    """
    For each test case, output the result of redacting the initial string A.

    A: the initial string
    B: the target string
    """
    result = list(A)
    j = 0
    for i in range(len(A)):
        if j < len(B) and A[i] == B[j]:
            j += 1
        else:
            result[i] = '#'
    return ''.join(result)