# -*- coding: utf-8 -*-
"""problem-5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9PLfUi4epMmVUgdYUr6I8JYpJjyqohr

Problem-7

Rank-2+2
"""

def solve(N, A):
    if N == 1:
        return [A[0]]

    if N == 2:
        best_cost = float('inf')
        best_b = [A[0], A[0]]

        for val in [A[0], A[1]]:
            b = [val, val]
            cost = get_cost(A, b)
            if cost < best_cost:
                best_cost = cost
                best_b = b

        return best_b

    if N == 3:
        best_cost = float('inf')
        best_b = A[:]

        for i in range(N):
            b = [A[i]] * N
            cost = get_cost(A, b)
            if cost < best_cost:
                best_cost = cost
                best_b = b

        b = A[:]
        cost = get_cost(A, b)
        if cost < best_cost:
            best_b = b

        return best_b

    return A[:]

def get_cost(A, B):
    N = len(A)
    total = 0

    for i in range(N - 1):
        total += abs(A[i] - A[i + 1])

    for i in range(N - 1):
        total += abs(B[i] - B[i + 1])

    for i in range(N):
        total += abs(A[i] - B[i])

    return total

def main():
    T = int(input())
    for _ in range(T):
        N = int(input())
        A = list(map(int, input().split()))
        result = solve(N, A)
        print(' '.join(str(x) for x in result))

if __name__ == '__main__':
    main()

