# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UffaggLLHogGZFh36e5VVMK5YS4bzyC0
"""

import sys

input = sys.stdin.readline

def censor_this_please():
    a_str = input().strip()
    b_str = input().strip()

    p = 0
    q = 0
    out = []

    while p < len(a_str):
        if q < len(b_str) and a_str[p] == b_str[q]:
            out.append(a_str[p])
            q += 1
        else:
            out.append('#')
        p += 1

    print(''.join(out))


def main():
    t_cases = int(input())

    for _ in range(t_cases):
        censor_this_please()


main()