# -*- coding: utf-8 -*-
"""Problem4B1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSw4W9tMj7LwdPYQ-lpLigBcQaMzRZ-T
"""

import math
input = """4
3 10 10 1 1
0 0
2 2
9 9
3 6 8 2 1
1 1
1 5
5 1
3 6 8 2 1
1 1
2 3
4 4
3 5 5 2 3
2 2
0 0
1 4
"""
def egcd(a, b):
    if b == 0:
        return a, 1, 0
    g, x, y = egcd(b, a % b)
    return g, y, x - (a // b) * y

def modinv(a, m):
    g, x, _ = egcd(a, m)
    if g != 1:
        return None
    return x % m

def crt(a, n, b, m):
    g, x, _ = egcd(n, m)
    if (b - a) % g != 0:
        return None, None
    lcm = n // g * m
    t = (a + ((b - a) // g) * x % (m // g) * n) % lcm
    return t, lcm

def solve(data):
    it = iter(data.strip().split())
    T = int(next(it))
    out = []

    for _ in range(T):
        K = int(next(it))
        N = int(next(it))
        M = int(next(it))
        P = int(next(it))
        Q = int(next(it))

        lazarbeam = (Q, P)

        ast = [(int(next(it)), int(next(it))) for _ in range(K)]
        x0, y0 = ast[0]

        g1 = math.gcd(Q, N)
        n1 = N // g1
        invQ = modinv(Q // g1, n1)

        g2 = math.gcd(P, M)
        n2 = M // g2
        invP = modinv(P // g2, n2)

        cycle = (n1 * n2) // math.gcd(n1, n2)

        best_t = None
        best_i = 0

        for i, (xi, yi) in enumerate(ast):
            dx = (xi - x0) % N
            dy = (yi - y0) % M

            if dx % g1 or dy % g2:
                continue

            a = (dx // g1) * invQ % n1
            b = (dy // g2) * invP % n2

            t, _ = crt(a, n1, b, n2)
            if t is None:
                continue

            if t == 0:
                t = cycle

            if best_t is None or t < best_t:
                best_t = t
                best_i = i

        out.append(str(best_i))

    return "\n".join(out)

print(solve(input))

def read_your_input():
    return input