# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HOQXcCx9vkpmeFgS7hhWhypGqDphd7gU
"""

def solve():

    all_num = list(map(int, input().split()))

    indx = 0
    T = all_num[indx]
    indx += 1

    for i in range(T):
        L = all_num[indx]
        W = all_num[indx + 1]
        E = all_num[indx + 2]
        R = all_num[indx + 3]
        indx += 4

        area = 2 * (L + W)
        energyperlap = area * R
        laps = E // energyperlap

        print(laps)


def read_your_input():
    solve()


if __name__ == "__main__":
    read_your_input()