# -*- coding: utf-8 -*-
"""CALICO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WuB6jKxMQQu5tRpJVC-kAieR5r3eEFAd
"""

def solve(line1, line2):
    N, P, R, K = map(int, line1.split())
    E = list(map(int, line2.split()))

    dylan_power = P

    for i in range(N):
        dylan_power -= E[i]
        if dylan_power < 0:
            print("nah i'd lose")
            return
        if (i + 1) % K == 0:
            dylan_power += R

    print("nah i'd win")

def read_your_input(raw):
    data = [line.strip() for line in raw.splitlines() if line.strip()]
    idx = 0
    T = int(data[idx]); idx += 1
    for _ in range(T):
        solve(data[idx], data[idx+1])
        idx += 2

test_input = """6
5 60 5 1
12 6 23 8 10
4 42 10 3
40 10 5 8
3 10 5 2
5 5 5 3
20 50 3 10
10 10 10 4
5 10 1 4
10 10 10 1
10 100 1 15"""

read_your_input(test_input)