# -*- coding: utf-8 -*-
"""CALICO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WuB6jKxMQQu5tRpJVC-kAieR5r3eEFAd
"""

def solve(data):
    it = iter(data.strip().split())
    t = int(next(it))
    results = []

    for _ in range(t):
        N = int(next(it))
        P = int(next(it))
        R = int(next(it))
        K = int(next(it))

        E = [int(next(it)) for _ in range(N)]

        dylan_power = P
        win = True

        for i in range(N):
            dylan_power -= E[i]

            if dylan_power < 0:
                win = False
                break

            if (i + 1) % K == 0:
                dylan_power += R

        results.append("nah i'd win" if win else "nah i'd lose")

    return "\n".join(results)


# paste your input here 👇
data = """6
5 60 5 1
12 6 23 8 10
4 42 10 3
40 10 5 8
3 10 5 2
5 5 5
3 20 50 3
10 10 10
4 5 10 1
4 10 10 10
1 10 100 1
15
"""

print(solve(data))