# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UffaggLLHogGZFh36e5VVMK5YS4bzyC0
"""

def censor_this_please(A, B):
    i = 0
    j = 0
    result = []

    while i < len(A):
        if j < len(B) and A[i] == B[j]:
            result.append(A[i])
            j += 1
        else:
            result.append('#')
        i += 1

    return ''.join(result)


def solve(input_file="input.txt", output_file="output.txt"):
    with open(input_file, "r") as f:
        data = [line.rstrip("\n") for line in f]

    t = int(data[0])
    idx = 1
    outputs = []

    for _ in range(t):
        A = data[idx]
        B = data[idx + 1]
        idx += 2
        outputs.append(censor_this_please(A, B))

    with open(output_file, "w") as f:
        f.write("\n".join(outputs))


if __name__ == "__main__":
    solve()