# -*- coding: utf-8 -*-
"""P3 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCaSV46gDWz5Iyic1W3JmWyqjGmpA16G
"""

def solve():
    test_cases = int(input())

    for _ in range(test_cases):
        string_a = input().strip()
        string_b = input().strip()

        pointer_b = 0
        ans = []

        for ch in string_a:
            if pointer_b < len(string_b) and ch == string_b[pointer_b]:
                ans.append(ch)
                pointer_b += 1
            else:
                ans.append('#')

        print("".join(ans))


if __name__ == "__main__":
    solve()