# -*- coding: utf-8 -*-
"""mycelium_bonus2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JpeBpTfGURd1x4d6WneaX_4IH84GIQg5
"""

import sys

def solve_case(xg, yg, xm, ym):
    dx = abs(xg - xm)
    dy = abs(yg - ym)
    d = dx + dy

    if d == 1:
        return 2

    k = (d - 1) // 6
    rem = (d - 1) % 6

    ans = 1 + 3 * k * (k + 1)

    if rem == 0:
        extra = 0
    elif rem == 1:
        extra = k + 1
    elif rem == 2:
        extra = 2 * k + 2
    elif rem == 3:
        extra = 3 * k + 3
    elif rem == 4:
        extra = 3 * k + 3 + (k + 1)
    else:
        extra = 3 * k + 3 + 2 * (k + 1)

    return ans + extra

def read_your_input():
    input = sys.stdin.readline
    t = int(input())
    for _ in range(t):
        xg, yg, xm, ym = map(int, input().split())
        print(solve_case(xg, yg, xm, ym))

if __name__ == "__main__":
    read_your_input()

import sys

def solve_case(xg, yg, xm, ym):
    dx = abs(xg - xm)
    dy = abs(yg - ym)
    d = dx + dy

    if d == 1:
        return 2

    k = (d - 1) // 6
    rem = (d - 1) % 6

    ans = 1 + 3 * k * (k + 1)

    if rem == 0:
        extra = 0
    elif rem == 1:
        extra = k + 1
    elif rem == 2:
        extra = 2 * k + 2
    elif rem == 3:
        extra = 3 * k + 3
    elif rem == 4:
        extra = 3 * k + 3 + (k + 1)
    else:
        extra = 3 * k + 3 + 2 * (k + 1)

    return ans + extra

def read_your_input():
    data = sys.stdin.read().strip().split()
    if not data:
        return
    t = int(data[0])
    idx = 1
    out = []
    for _ in range(t):
        xg = int(data[idx]); yg = int(data[idx+1])
        xm = int(data[idx+2]); ym = int(data[idx+3])
        idx += 4
        out.append(str(solve_case(xg, yg, xm, ym)))
    print("\n".join(out))

if __name__ == "__main__":
    read_your_input()