# -*- coding: utf-8 -*-
"""NahIdWin

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ig-yZ-VS95PTl5M8UPQGmdtNQh7nTHns
"""

Test_cases = int(input())   #test cases


for _ in range(Test_cases):
    play, power, heal, every = map(int,input().split())

    enemy = list(map(int,input().split()))  # enemy


    for i in range(play):
        power = power - enemy[i]

        if power < 0:
          print("nah i'd lose")
          break

        if (i + 1) % every == 0:
          power = power + heal


    else:
        print("nah i'd win")