# -*- coding: utf-8 -*-
"""answers_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11a7wdm_Qu4fb8cpRwaJbv1_HP_xQ-2HC
"""

import sys
input = sys.stdin.readline

T = int(input())

for _ in range(T):
    N, M, K = map(int, input().split())
    johnny_d_lecture = [input().strip() for _ in range(N)]

    seats = []


    left = [[0]*M for _ in range(N)]
    right = [[0]*M for _ in range(N)]

    for r in range(N):
        cnt = 0
        for c in range(M):
            left[r][c] = cnt
            if johnny_d_lecture[r][c] == '#':
                cnt += 1

        cnt = 0
        for c in reversed(range(M)):
            right[r][c] = cnt
            if johnny_d_lecture[r][c] == '#':
                cnt += 1

    for r in range(N):
        for c in range(M):
            if johnny_d_lecture[r][c] == '-':
                aura = min(left[r][c], right[r][c])
                u = r + c
                v = r - c
                seats.append((u, v, r, c, aura))

    seats.sort()

    def check(D):
        import heapq
        v_min_heap = []
        v_max_heap = []
        j = 0

        for i in range(len(seats)):
            while j < len(seats) and seats[j][0] - seats[i][0] <= D:
                v = seats[j][1]
                heapq.heappush(v_min_heap, (v, j))
                heapq.heappush(v_max_heap, (-v, j))
                j += 1

            while True:
                if not v_min_heap or not v_max_heap:
                    break

                while v_min_heap and v_min_heap[0][1] < i:
                    heapq.heappop(v_min_heap)
                while v_max_heap and v_max_heap[0][1] < i:
                    heapq.heappop(v_max_heap)

                if not v_min_heap or not v_max_heap:
                    break

                vmin = v_min_heap[0][0]
                vmax = -v_max_heap[0][0]

                if vmax - vmin <= D:
                    break
                else:
                    return None

            if j - i >= K:
                return i, j

        return None

    lo, hi = 0, 2000
    best = None

    while lo <= hi:
        mid = (lo + hi) // 2
        res = check(mid)
        if res:
            best = (mid, res)
            hi = mid - 1
        else:
            lo = mid + 1

    _, (i, j) = best

    candidates = seats[i:j]
    candidates.sort(key=lambda x: x[4])

    for k in range(K):
        _, _, r, c, _ = candidates[k]
        print(r, c)