# -*- coding: utf-8 -*-
"""problem-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9PLfUi4epMmVUgdYUr6I8JYpJjyqohr

**Rank_1**

Problem 1: Japan is turning footsteps into electricity
"""

def solve(L, W, E, R):
	p = 2 * (L + W)
	return E // (p * R)

def main():
	T = int(input())
	for _ in range(T):
		temp = input().split()
		L = int(temp[0])
		W = int(temp[1])
		E = int(temp[2])
		R = int(temp[3])

		print(solve(L, W, E, R))

if __name__ == "__main__":
	main()

