# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UffaggLLHogGZFh36e5VVMK5YS4bzyC0
"""

import sys

input = sys.stdin.readline

def solve():
    k_cnt, n_dim, m_dim, p_step, q_step = map(int, input().split())

    coords = []
    pos_map = {}

    for idx in range(k_cnt):
        x_val, y_val = map(int, input().split())
        coords.append((x_val, y_val))
        pos_map[(x_val, y_val)] = idx

    start_x, start_y = coords[0]

    cur_x = start_x
    cur_y = start_y

    visited = set()

    lazarbeam = True

    while True:
        cur_x = (cur_x + q_step) % n_dim
        cur_y = (cur_y + p_step) % m_dim

        if (cur_x, cur_y) in pos_map:
            print(pos_map[(cur_x, cur_y)])
            return

        if (cur_x, cur_y) in visited:
            print(0)
            return

        visited.add((cur_x, cur_y))


def main():
    t_cases = int(input())

    for _ in range(t_cases):
        solve()


main()