# -*- coding: utf-8 -*-
"""question8.1b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYNyYyH6dCkDBEStNlYvx75UUvyYxQPT
"""

import sys
from io import StringIO

def solve(xg, yg, xm, ym):
    dx = xm - xg
    dy = ym - yg

    LIM = 5000
    cnt = 0


    for x in range(-LIM, LIM + 1):
        for y in range(-LIM, LIM + 1):


            g = 2 * (abs(x) + abs(y))


            m = 7 * (abs(x - dx) + abs(y - dy))

            if m <= g:
                cnt += 1

    return cnt

def read_your_input():

    sample_input = """5
0 0 0 1
0 0 -1 -4
1 3 3 8
0 -6 7 0
-10 -10 10 10
"""


    sys.stdin = StringIO(sample_input)

    T = int(sys.stdin.readline())
    results = []
    for _ in range(T):
        xg, yg, xm, ym = map(int, sys.stdin.readline().split())
        results.append(str(solve(xg, yg, xm, ym)))
    print("\n".join(results))


if __name__ == "__main__":
    read_your_input()

