# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVhucHNsCmw85k_q8GSRZjqbUjvvD5NC
"""

import sys

# Helper function to simulate the spread for a single test case
def simulate_spread(xg, yg, xm, ym):
    grass = set([(xg, yg)])
    mycel = set([(xm, ym)])
    tick = 0

    while True:
        tick += 1
        new_grass = set()
        new_myc = set()

        # Grass spread (every even tick)
        if tick % 2 == 0:
            # Create a list to iterate over a snapshot of the set to avoid modifying during iteration
            for gx, gy in list(grass):
                for dx, dy in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
                    nx, ny = gx + dx, gy + dy
                    if (nx, ny) not in grass and (nx, ny) not in mycel:
                        new_grass.add((nx, ny))

        # Mycelium spread (every multiple of 7)
        if tick % 7 == 0:
            # Create a list to iterate over a snapshot of the set to avoid modifying during iteration
            for mx, my in list(mycel):
                for dx, dy in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
                    nx, ny = mx + dx, my + dy
                    if (nx, ny) not in grass and (nx, ny) not in mycel:
                        new_myc.add((nx, ny))

        # Resolve conflicts: if both try to claim a tile, grass wins
        overlap = new_grass & new_myc
        grass.update(new_grass)
        mycel.update(new_myc - overlap) # Mycelium cannot spread to cells grass claims

        # Stop condition: if mycelium did not spread on its tick, it won't spread further
        if tick % 7 == 0 and not new_myc:
            break

    return len(mycel)

def main():
    # Use sys.stdin.read to read all input at once, then split by whitespace
    input_content = sys.stdin.read()
    data = input_content.split()

    # Handle case where no input is provided or input is empty
    if not data:
        print("Error: No input provided or input is empty.")
        print("Please provide input data in the format: T (number of test cases) followed by 4 coordinates per test case.")
        return

    try:
        # The first element is the number of test cases
        T = int(data[0])
        index = 1 # Start index for coordinates

        results = []
        for i in range(T):
            # Ensure there are enough elements for the current test case
            # Each test case requires 4 integers (xg, yg, xm, ym)
            if index + 3 >= len(data):
                print(f"Error: Not enough input data for test case {i + 1}. Expected 4 coordinates but found less. Stopping.")
                break

            xg = int(data[index])
            yg = int(data[index + 1])
            xm = int(data[index + 2])
            ym = int(data[index + 3])
            index += 4

            # Simulate and store result
            results.append(simulate_spread(xg, yg, xm, ym))

        # Print all results
        for res in results:
            print(res)

    except ValueError as e:
        print(f"Error processing input: {e}. Ensure all input values are integers.")
    except IndexError as e:
        print(f"Error accessing data: {e}. Please check the input format and ensure sufficient data is provided.")

if __name__ == "__main__":
    main()