# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVhucHNsCmw85k_q8GSRZjqbUjvvD5NC
"""

import sys

def main():
    # Use sys.stdin.read to read all input at once, then split by whitespace
    input_content = sys.stdin.read()
    data = input_content.split()

    # Handle case where no input is provided or input is empty
    if not data:
        print("Error: No input provided or input is empty.")
        print("Please provide input data in the format: T (number of test cases) followed by 4 coordinates per test case.")
        return

    try:
        # The first element is the number of test cases
        T = int(data[0])
        index = 1 # Start index for coordinates

        results = []
        for i in range(T):
            # Ensure there are enough elements for the current test case
            # Each test case requires 4 integers (xg, yg, xm, ym)
            if index + 3 >= len(data):
                print(f"Error: Not enough input data for test case {i + 1}. Expected 4 coordinates but found less. Stopping.")
                break

            xg = int(data[index])
            yg = int(data[index + 1])
            xm = int(data[index + 2])
            ym = int(data[index + 3])
            index += 4

            # Calculate Manhattan distance between grass and mycelium start points
            D = abs(xg - xm) + abs(yg - ym)

            # Calculate K using the optimized formula
            # This formula comes from analyzing the relative spread rates:
            # Grass spreads 1 unit in 2 ticks, Mycelium spreads 1 unit in 7 ticks.
            # A cell (x,y) is claimed by Mycelium if 7 * d_m < 2 * d_g
            # where d_m is Manhattan distance from mycelium origin and d_g from grass origin.
            # This inequality defines a diamond shape region for mycelium, and K is its radius.
            # The specific values (2 and 7) lead to the denominator 9 (2+7) and numerator related to 2*D.
            K = (2 * D - 1) // 9

            # If K is negative (e.g., for D=0, K=-1/9 -> 0), it means no spread beyond initial cell.
            # The formula 1 + 2*K*(K+1) is valid for K >= 0.
            # If K < 0, it means the grass is so close and fast that mycelium cannot even expand one unit.
            # In this case, mycelium only holds its initial spot, so area is 1.
            # The formula 1 + 2*K*(K+1) naturally gives 1 for K=0.
            # For D=0, K = -1//9 = -1, which would make the formula wrong. Let's ensure K is at least 0.
            if K < 0:
                K = 0

            # The number of cells in a diamond (L1 ball) of radius K is 1 + 2 * K * (K + 1)
            ans = 1 + 2 * K * (K + 1)

            # Store result
            results.append(ans)

        # Print all results
        for res in results:
            print(res)

    except ValueError as e:
        print(f"Error processing input: {e}. Ensure all input values are integers.")
    except IndexError as e:
        print(f"Error accessing data: {e}. Please check the input format and ensure sufficient data is provided.")

if __name__ == "__main__":
    main()