# -*- coding: utf-8 -*-
"""P1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QCaSV46gDWz5Iyic1W3JmWyqjGmpA16G
"""

def solve():
    t = int(input())

    for _ in range(t):
        L, W, E, R = map(int, input().split())

        pm = 2 * (L + W)
        ele_per_lap = pm * R
        laps = E // ele_per_lap

        print(laps)


if __name__ == "__main__":
    solve()