# -*- coding: utf-8 -*-
"""prob8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/172LOkOKWHQeqlbzp0jEkJ4IOZYS7xNSe
"""

import sys

def solve():

    input_data = sys.stdin.read().split()
    if not input_data:
        return

    T = int(input_data[0])
    idx = 1

    for _ in range(T):
        xg = int(input_data[idx])
        yg = int(input_data[idx+1])
        xm = int(input_data[idx+2])
        ym = int(input_data[idx+3])
        idx += 4

        gx = xg - xm
        gy = yg - ym


        D = abs(gx) + abs(gy)

        R_safe = (2 * D + 4) // 5

        total_mycelium_tiles = calculate_enclosed_area(gx, gy, D, R_safe)
        print(total_mycelium_tiles)

def calculate_enclosed_area(gx, gy, D, R_safe):

    pass

if __name__ == '__main__':
    solve()