# -*- coding: utf-8 -*-
"""prob8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/172LOkOKWHQeqlbzp0jEkJ4IOZYS7xNSe
"""

import collections

def solve():
    try:
        line = input().split()
        if not line: return
        xg, yg, xm, ym = map(int, line)
    except EOFError:
        return

    q = collections.deque([(xm, ym)])
    visited = {(xm, ym)}
    count = 0

    while q:
        cx, cy = q.popleft()

        dist_g = abs(cx - xg) + abs(cy - yg)
        dist_m = abs(cx - xm) + abs(cy - ym)

        if 7 * dist_m < 2 * dist_g:
            count += 1

            for dx, dy in [(0,1), (0,-1), (1,0), (-1,0)]:
                nx, ny = cx + dx, cy + dy
                if (nx, ny) not in visited:
                    visited.add((nx, ny))
                    q.append((nx, ny))

    print(count)

def main():
    line = input().strip()
    if line:
        t = int(line)
        for _ in range(t):
            solve()

if __name__ == "__main__":
    main()