# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LkZ2SdiZNoTR1TUsFy1jP4vjD3c2o-8R
"""

import sys
input = sys.stdin.readline

def construct(P, A, B):
    # Extract mixed radix digits
    digits = []

    for _ in range(B):
        digits.append(P % 3)
        P //= 3

    for _ in range(A):
        digits.append(P % 2)
        P //= 2

    n = len(digits) + 2
    m = 3
    grid = [["." for _ in range(m)] for _ in range(n)]

    # Start
    grid[0][1] = 'v'

    r = 1
    for i, d in enumerate(digits):
        grid[r][1] = 'S'

        # Left and right branches
        if i < B:
            # Ternary logic (simulate with 2 outputs + drop)
            if d == 0:
                grid[r][0] = 'v'
                grid[r][2] = 'X'
            elif d == 1:
                grid[r][0] = 'X'
                grid[r][2] = 'v'
            else:
                grid[r][0] = 'X'
                grid[r][2] = 'X'
        else:
            # Binary
            if d == 0:
                grid[r][0] = 'v'
                grid[r][2] = 'X'
            else:
                grid[r][0] = 'X'
                grid[r][2] = 'v'

        # Continue downward
        grid[r][1] = 'v'
        r += 1

    # Final row (exit path)
    grid[r][1] = 'v'
    grid[r][0] = 'X'
    grid[r][2] = '.'

    return n, m, grid


def solve():
    t = int(input())
    for _ in range(t):
        P, A, B = map(int, input().split())
        n, m, grid = construct(P, A, B)
        print(n, m)
        for row in grid:
            print("".join(row))


if __name__ == "__main__":
    solve()