# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LkZ2SdiZNoTR1TUsFy1jP4vjD3c2o-8R
"""

import sys
input = sys.stdin.readline

def solve():
    t = int(input())
    for _ in range(t):
        P, A, B = map(int, input().split())

        # Total leaves
        total = (2 ** A) * (3 ** B)

        # Build decisions (mixed radix)
        decisions = []

        for _ in range(B):
            decisions.append(P % 3)
            P //= 3

        for _ in range(A):
            decisions.append(P % 2)
            P //= 2

        # Grid size (safe bound)
        n = 2 * len(decisions) + 5
        m = 5
        grid = [["." for _ in range(m)] for _ in range(n)]

        r, c = 0, 2
        grid[r][c] = 'v'
        r += 1

        for i, d in enumerate(decisions):
            grid[r][c] = 'S'

            if i < B:
                # 3-way split: left, down, right
                # We allow all 3 directions
                grid[r][c-1] = '<'
                grid[r][c+1] = '>'
                grid[r][c] = 'v'

                # Block invalid backward flows
                grid[r][c-2] = 'X'
                grid[r][c+2] = 'X'

                # Route based on digit
                if d == 0:
                    grid[r][c+1] = 'X'
                    grid[r][c] = 'v'
                elif d == 1:
                    grid[r][c-1] = 'X'
                    grid[r][c] = 'v'
                else:
                    grid[r][c-1] = 'X'
                    grid[r][c+1] = 'X'

            else:
                # 2-way split
                grid[r][c-1] = '<'
                grid[r][c+1] = '>'

                if d == 0:
                    grid[r][c+1] = 'X'
                else:
                    grid[r][c-1] = 'X'

                grid[r][c] = 'v'

            r += 1

        # Final row: exit vs destroy
        grid[r][c] = 'v'
        grid[r][c-1] = 'X'
        grid[r][c+1] = '.'

        # Trim grid
        out = []
        for row in grid:
            out.append("".join(row))

        print(n, m)
        for row in out:
            print(row)


if __name__ == "__main__":
    solve()