# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IVhucHNsCmw85k_q8GSRZjqbUjvvD5NC
"""

import sys
import bisect
input = sys.stdin.readline

def solve():
    N = int(input())
    A = list(map(int, input().split()))

    if N == 1:
        print(A[0])
        return

    ranges = []
    L = [A[0]]
    R = [A[0]]
    ranges.append((L[-1], R[0]))

    for i in range(1, N):
        ai = A[i]

        # Inf-conv with |.|: remove leftmost of L and rightmost of R if size > 1
        if len(L) > 1:
            L.pop(0)
        if len(R) > 1:
            R.pop(-1)

        # Add |v - ai|: insert ai into both L and R
        bisect.insort(L, ai)
        bisect.insort(R, ai)

        # Rebalance: ensure L_max <= R_min
        if L[-1] > R[0]:
            lv = L.pop(-1)
            rv = R.pop(0)
            bisect.insort(L, rv)
            bisect.insort(R, lv)

        ranges.append((L[-1], R[0]))

    # Reconstruct b from right to left
    b = [0] * N
    b[N-1] = max(ranges[N-1][0], min(ranges[N-1][1], A[N-1]))
    for i in range(N-2, -1, -1):
        b[i] = max(ranges[i][0], min(ranges[i][1], b[i+1]))

    # Ensure bi >= 1
    b = [max(1, x) for x in b]
    print(*b)

def main():
    T = int(input())
    for _ in range(T):
        solve()

if __name__ == "__main__":
    main()