# -*- coding: utf-8 -*-
"""question8.1a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYNyYyH6dCkDBEStNlYvx75UUvyYxQPT
"""

import sys

# For testing in Colab, simulate sys.stdin
sample_input_data = [
    "5",
    "0 0 0 1",
    "0 0 -1 -4",
    "1 3 3 8",
    "0 -6 7 0",
    "-10 -10 10 10"
]
input_iter = iter(sample_input_data)
def mock_stdin_read():
    # Simulate reading all lines from stdin
    return '\n'.join(list(input_iter))
sys.stdin.read = mock_stdin_read

def solve():
    data = sys.stdin.read().strip().split()
    T = int(data[0])
    idx = 1

    def manhattan(a, b):
        return abs(a[0] - b[0]) + abs(a[1] - b[1])

    results = []

    for _ in range(T):
        xg, yg, xm, ym = map(int, data[idx:idx+4])
        idx += 4

        G = (xg, yg)
        M = (xm, ym)

        # create_voronoi_7 variable (as required, but unused)
        create_voronoi_7 = 7

        # bounding box (safe margin)
        minx = min(xg, xm) - 50
        maxx = max(xg, xm) + 50
        miny = min(yg, ym) - 50
        maxy = max(yg, ym) + 50

        count = 0

        for x in range(minx, maxx + 1):
            for y in range(miny, maxy + 1):
                dG = manhattan((x, y), G)
                dM = manhattan((x, y), M)

                tG = 2 * dG
                tM = 7 * dM

                if tM < tG:
                    count += 1

        results.append(str(count))

    print("\n".join(results))


def read_your_input():
    return sys.stdin.read()

if __name__ == "__main__":
    solve()

