# -*- coding: utf-8 -*-
"""piezoelectric

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WhSg5RJcdnW_kpceFgqXNPeIqH_EH3nk
"""

# 2 * (L + W)
# E / (Perimeter * R)

Total_test_cases = int(input())

for i in range(Total_test_cases):
    length, width, energy, rate = map(int, input().split())

    perimeter = 2 * (length + width)
    laps = energy // (perimeter * rate)
    result = int(laps)

    print(result)