# -*- coding: utf-8 -*-
"""Grid Fill.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7oKBA9xZS1Dr8mZU7GkDhRrTqVT0hOa
"""

import statistics

def solve():
    try:
        t_line = input()
        if not t_line: return
        T = int(t_line.strip())
    except EOFError:
        return

    for _ in range(T):
        N = int(input().strip())
        tower_heights = list(map(int, input().split()))

        tower_heights.sort()
        median_val = tower_heights[N // 2]

        reconstructed_bottom_tower = [median_val] * N

        print(*(reconstructed_bottom_tower))

if __name__ == "__main__":
    solve()