# -*- coding: utf-8 -*-
"""problem1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oTIHSnxBCrKwHFpuzZe5-r3iFP3w765Z
"""

t = int(input())

for _ in range(t):
    L, W, E, R = map(int, input().split())

    triangle_area = 2 * (L + W)
    electricity_per_lap = triangle_area * R

    laps = E // electricity_per_lap
    print(laps)

