# -*- coding: utf-8 -*-
"""q6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RYNyYyH6dCkDBEStNlYvx75UUvyYxQPT
"""

import sys
# input = sys.stdin.readline # Original line commented out

# For testing in Colab, simulate sys.stdin.readline
# Replace this with actual input for competitive programming platforms
sample_input_data = [
  "6",
  "2",
  "##",
  "##",
  "##",
  "##",
  "3",
  "#.#",
  "#.#",
  "###",
  "#.#",
  "#.#",
  "###",
  "3",
  "#.#",
  "#.#",
  "###",
  "###",
  "#.#",
  "#.#",
  "3",
  "#.#",
  "#.#",
  "###",
  "###",
  "##.",
  "##.",
  "4",
  "#...",
  "..##",
  "##.#",
  "##..",
  "..##",
  "..##",
  "##.#",
  "#.##",
  "2",
  "..",
  "..",
  "..",
  ".."
]
input_iter = iter(sample_input_data)
def mock_input():
    return next(input_iter) + "\n" # Add newline as readline usually does

input = mock_input # Assign our mock function to 'input'

def solve():
    t = int(input())
    for _ in range(t):
        n = int(input())

        S1 = [input().strip() for _ in range(n)]
        S2 = [input().strip() for _ in range(n)]

        max_vol = 0
        min_vol = 0

        jugs_cave_image = 0

        for i in range(n):
            a = S1[i].count('#')
            b = S2[i].count('#')

            max_vol += a * b
            min_vol += max(a, b)

        print(max_vol, min_vol)

def read_your_input():
    solve()


if __name__ == "__main__":
    read_your_input()

