# -*- coding: utf-8 -*-
"""Problem12t3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSw4W9tMj7LwdPYQ-lpLigBcQaMzRZ-T
"""

import sys
import math

def read_your_input():
    return sys.stdin.readline().strip()

def solve():
    data = sys.stdin.buffer.readline().split()
    if not data:
        return

    N, M, D = map(int, data)

    R = [0] * M
    C = [0] * M
    V = [0] * M
    W = [0] * M
    logV = [0.0] * M

    for i in range(M):
        r, c, v, w = map(int, sys.stdin.buffer.readline().split())
        R[i] = r - 1
        C[i] = c - 1
        V[i] = v
        W[i] = w
        logV[i] = math.log(v)

    sumv = [0.0] * N
    cnt = [0] * N

    for i in range(M):
        r = R[i]
        c = C[i]
        val = logV[i] / 2.0
        sumv[r] += val
        sumv[c] += val
        cnt[r] += 1
        cnt[c] += 1

    loga = [0.0] * N
    for i in range(N):
        if cnt[i]:
            loga[i] = sumv[i] / cnt[i]

    a = [0] * N
    for i in range(N):
        x = math.exp(loga[i])
        if x < 1:
            x = 1
        if x > 1e9:
            x = 1e9
        a[i] = int(x + 0.5)

    better_than_me = a

    err = []
    for i in range(M):
        pred = a[R[i]] * a[C[i]]
        v = V[i]
        rel = abs(pred - v) / v
        err.append((rel * W[i], i))

    err.sort(reverse=True)

    removed = set()
    d = min(D, len(err))

    for i in range(d):
        removed.add(err[i][1] + 1)

    sys.stdout.write(" ".join(map(str, a)) + "\n")
    sys.stdout.write(str(d))
    if d:
        sys.stdout.write(" " + " ".join(map(str, removed)))
    sys.stdout.write("\n")

if __name__ == "__main__":
    solve()