# -*- coding: utf-8 -*-
"""Problem12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSw4W9tMj7LwdPYQ-lpLigBcQaMzRZ-T
"""

import sys
import math

def read_your_input():
    return sys.stdin.readline().strip()

def solve():
    data = sys.stdin.buffer.readline().split()
    if not data:
        return
    N, M, D = map(int, data)
    R = [0] * M
    C = [0] * M
    V = [0] * M
    W = [0] * M

    for i in range(M):
        r, c, v, w = map(int, sys.stdin.buffer.readline().split())
        R[i] = r - 1
        C[i] = c - 1
        V[i] = v
        W[i] = w
    loga = [0.0] * N
    cnt = [0] * N
    for _ in range(4):
        sumv = [0.0] * N
        cnt = [0] * N

        for i in range(M):
            r = R[i]
            c = C[i]
            if V[i] <= 0:
                continue
            val = math.log(V[i])

            sumv[r] += val - loga[c]
            sumv[c] += val - loga[r]
            cnt[r] += 1
            cnt[c] += 1

        for i in range(N):
            if cnt[i]:
                loga[i] = sumv[i] / cnt[i]
    a = [0] * N
    for i in range(N):
        x = math.exp(loga[i])
        x = max(1.0, min(1e9, x))
        a[i] = int(x + 0.5)
    err = []
    for i in range(M):
        r = R[i]
        c = C[i]
        pred = a[r] * a[c]
        v = V[i]
        rel = abs(pred - v) / max(1.0, v)
        score = rel * W[i]
        err.append((score, i))

    err.sort(reverse=True)

    discard = set()
    d = min(D, len(err))
    for i in range(d):
        discard.add(err[i][1])
    sys.stdout.write(" ".join(map(str, a)) + "\n")
    sys.stdout.write(str(d))
    if d:
        sys.stdout.write(" " + " ".join(str(i + 1) for i in discard))
    sys.stdout.write("\n")

if __name__ == "__main__":
    solve()