# -*- coding: utf-8 -*-
"""Calico Prob No 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aik-ce6tz68d7ORtsZZSjey3qHX8xEwT
"""

# Problem No 01

import sys

def solve():
    data = sys.stdin.read().split()
    if not data:
        return

    T = int(data[0])
    idx = 1
    results = []

    for _ in range(T):
        L = int(data[idx])
        W = int(data[idx+1])
        E = int(data[idx+2])
        R = int(data[idx+3])
        idx += 4


        triangle_area = 2 * (L + W)

        energy_per_lap = triangle_area * R
        ans = E // energy_per_lap
        results.append(str(ans))

    sys.stdout.write('\n'.join(results) + '\n')

def read_your_input():
    solve()

if __name__ == '__main__':
    read_your_input()