# -*- coding: utf-8 -*-
"""Problem10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSw4W9tMj7LwdPYQ-lpLigBcQaMzRZ-T
"""

def solve(P, A, B):
    grid = []

    splits = A + B
    if splits == 0:
        return ["1 1", ">"]

    width = 2 * splits + 3
    grid = [['.' for _ in range(width)] for _ in range(3)]

    grid[1][0] = '>'

    twos, threes = A, B
    collect_needed = P

    col = 1
    for i in range(splits):
        grid[1][col] = 'S'

        if threes > 0:
            threes -= 1
            grid[0][col] = '^'
            grid[2][col] = 'X'
            grid[1][col + 1] = '>'
            col += 2
        else:
            twos -= 1
            grid[0][col] = '^'
            grid[1][col + 1] = '>'
            col += 2

    grid[1][col] = 'X'

    up_cols = [c for c in range(1, width, 2) if grid[0][c] == '^']

    for idx, c in enumerate(up_cols):
        if idx >= collect_needed:
            grid[0][c] = 'X'

    while len(grid[0]) > 1 and all(row[-1] == '.' for row in grid):
        for r in range(3):
            grid[r].pop()

    h, w = len(grid), len(grid[0])
    res = [f"{h} {w}"]
    for row in grid:
        res.append(''.join(row))

    return res

t = 1
tests = [
    (1, 1, 1)
]


for P, A, B in tests:
    ans = solve(P, A, B)
    print("\n".join(ans))