# -*- coding: utf-8 -*-
"""problem-4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V9PLfUi4epMmVUgdYUr6I8JYpJjyqohr

Problem-12

Rank-1+3
"""

def solve(K, N, M, P, Q, X, Y):
    x, y = X[0], Y[0]

    # Create set for fast lookup
    targets = set()
    for i in range(1, K):
        targets.add((X[i], Y[i]))

    steps = 0
    while steps < N * M:
        # Move laser
        x = (x + Q) % N
        y = (y + P) % M
        steps += 1

        # Check if hit any asteroid
        pos = (x, y)
        if pos in targets:
            for i in range(1, K):
                if X[i] == x and Y[i] == y:
                    return i

        # Check if back to start
        if x == X[0] and y == Y[0]:
            return 0

    return 0

def main():
    T = int(input())

    for _ in range(T):
        line = input().split()
        K = int(line[0])
        N = int(line[1])
        M = int(line[2])
        P = int(line[3])
        Q = int(line[4])

        X = []
        Y = []
        for _ in range(K):
            coords = input().split()
            a_i = int(coords[0])
            b_i = int(coords[1])
            X.append(a_i)
            Y.append(b_i)

        print(solve(K, N, M, P, Q, X, Y))

if __name__ == '__main__':
    main()

